package com.miniproject.backend.skills;

import com.miniproject.backend.artifact.Evidence;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

/**
 * Deterministic template-fill fallback — no AI reasoning about what a sane
 * config looks like, just fills the real answers into a skeleton whose key
 * names mirror the actual Hermes EmailAdapter constructor (incident_report_directory,
 * incident_extract_directory, incident_project_root, SharePoint download dir --
 * read from the real source, not guessed). Placeholders only for genuine
 * secrets (tokens/passwords/credentials); every other answer goes in as-is.
 */
@Component
public class RuleBasedHermesSetupWizardSynthesizer implements HermesSetupWizardSynthesizer {

    @Override
    public HermesSetupWizardResult synthesize(HermesSetupWizardAnswers answers) {
        String yaml = buildYaml(answers);
        List<String> checklist = buildChecklist(answers);
        List<String> notes = List.of(
                "Generated by the rule-based fallback (no AI provider configured) — fills in your real answers, "
                        + "but doesn't reason about whether this shape matches Hermes's actual config schema.",
                "This content is never written into Hermes's own files automatically — copy it in by hand.");
        List<Evidence> evidence = List.of(
                new Evidence("Generated setup skeleton for " + answers.repoPath(), "hermes-setup-wizard (rule-based)"));
        return new HermesSetupWizardResult(answers, yaml, checklist, notes, evidence);
    }

    private String buildYaml(HermesSetupWizardAnswers answers) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by mini-Project's Hermes Setup Wizard — review before applying.\n");
        sb.append("description: \"Incident-response profile for ").append(answers.repoPath()).append("\"\n");
        sb.append("description_auto: false\n\n");

        sb.append("platforms:\n");
        if (answers.hasPlatform("discord")) {
            sb.append("  discord:\n");
            sb.append("    enabled: true\n");
            sb.append("    bot_token: \"<FILL_IN_DISCORD_BOT_TOKEN>\"\n");
            sb.append("    intake_channel_id: \"").append(orPlaceholder(answers.discordChannelId(), "FILL_IN_CHANNEL_ID")).append("\"\n");
        }
        if (answers.hasPlatform("email")) {
            sb.append("  email:\n");
            sb.append("    enabled: true\n");
            sb.append("    imap_host: \"").append(orPlaceholder(answers.emailImapHost(), "FILL_IN_IMAP_HOST")).append("\"\n");
            sb.append("    account: \"").append(orPlaceholder(answers.emailAccount(), "FILL_IN_EMAIL_ACCOUNT")).append("\"\n");
            sb.append("    app_password: \"<FILL_IN_APP_PASSWORD>\"\n");
            sb.append("    allowed_senders:\n");
            List<String> senders = answers.emailAllowedSenders();
            if (senders == null || senders.isEmpty()) {
                sb.append("      - \"<FILL_IN_ALLOWED_SENDER>\"\n");
            } else {
                for (String sender : senders) {
                    sb.append("      - \"").append(sender).append("\"\n");
                }
            }
        }

        sb.append('\n');
        sb.append("incident_project_root: \"").append(answers.repoPath()).append("\"\n");
        appendIfPresent(sb, "incident_report_directory", answers.incidentReportsDir());
        appendIfPresent(sb, "incident_extract_directory", answers.incidentExtractsDir());
        appendIfPresent(sb, "incident_downloads_directory", answers.incidentDownloadsDir());
        appendIfPresent(sb, "server_log_path", answers.serverLogPath());

        sb.append('\n');
        sb.append("pr_package:\n");
        sb.append("  enabled: ").append(answers.prPackageEnabled()).append('\n');
        if (answers.prPackageEnabled()) {
            sb.append("  git_host: \"").append(orPlaceholder(answers.gitHost(), "FILL_IN_GIT_HOST")).append("\"\n");
            sb.append("  credentials: \"<FILL_IN_GIT_CREDENTIALS>\"\n");
        }
        return sb.toString();
    }

    private void appendIfPresent(StringBuilder sb, String key, String value) {
        if (value != null && !value.isBlank()) {
            sb.append(key).append(": \"").append(value.trim()).append("\"\n");
        }
    }

    private String orPlaceholder(String value, String placeholderName) {
        return value == null || value.isBlank() ? "<" + placeholderName + ">" : value.trim();
    }

    private List<String> buildChecklist(HermesSetupWizardAnswers answers) {
        List<String> items = new ArrayList<>();
        items.add("Confirm the repo path is correct and readable by the Hermes process.");
        if (answers.hasPlatform("discord")) {
            items.add("Create/obtain a Discord bot token and invite it to the intake channel.");
        }
        if (answers.hasPlatform("email")) {
            items.add("Provide the real email app-specific password (not the account password).");
            if (answers.emailAllowedSenders() == null || answers.emailAllowedSenders().isEmpty()) {
                items.add("You didn't list any allowed senders — every incoming email will be rejected until you add at least one.");
            }
        }
        if (answers.incidentReportsDir() == null || answers.incidentReportsDir().isBlank()) {
            items.add("No incident-reports directory given — Hermes will fall back to its own default location.");
        }
        if (answers.prPackageEnabled()) {
            items.add("Provide git host credentials for the PR-package push/PR flow.");
        }
        items.add("Review the generated YAML against Hermes's own config schema before applying — this is a "
                + "generic skeleton, not validated against the real config.yaml structure.");
        items.add("Apply by hand into Hermes's profile — this wizard does not write files for you.");
        return items;
    }
}
